function out = divcurlfreeM2(X)
    out = [sqrt(2)*cosh(sqrt(2)*X(:,1)).*cos(X(:,2)).*cos(X(:,3)) ...
           -sinh(sqrt(2)*X(:,1)).*sin(X(:,2)).*cos(X(:,3)) ...
           -sinh(sqrt(2)*X(:,1)).*cos(X(:,2)).*sin(X(:,3))];
end