% Function to plot the field generated by the scalar potential
% u(x) = -SL(Tnu)(x) + DL(Tdu)(x)
% tilde{H} = grad u
% Computing grad u = -grad SL(Tnu)(x) + grad DL(Tdu)(x)

function out = plot_field_scalar_potential(bndmesh,Tdu,Tnu,J,omega_src)
    % BEM Spaces
    P0 = fem(bndmesh,'P0');
    P1 = fem(bndmesh,'P1');

    Gamma = dom(bndmesh,3);
    normals = Gamma.qudNrm;

    % Computing psi and g at quadrature points
    psi = reconstruct(Tnu,Gamma,P0);
    g = reconstruct(Tdu,Gamma,P1);

    % Evaluation points for grad u
    maxGamma = max(bndmesh.vtx);
    minGamma = min(bndmesh.vtx);
    meanGamma = 0.5*(maxGamma+minGamma);
    newMinGamma = 2 * minGamma - meanGamma;
    newMaxGamma = 2 * maxGamma - meanGamma;

    N = 20;
    x = linspace(newMinGamma(1),newMaxGamma(1),N);
    y = linspace(newMinGamma(2),newMaxGamma(2),N);

    [X,Y] = meshgrid(x,y);
    X = reshape(X,[N*N,1]);
    Y = reshape(Y,[N*N,1]);
    Z = meanGamma(3) * ones(N*N,1);

    eval_pts = [X,Y,Z];
    
    tildeH = -computeGradSLLaplace(bndmesh,Tnu,eval_pts) + computeGradDLLaplace(bndmesh,Tdu,eval_pts);
    HJ = compute_vecpot_curl(J,omega_src,eval_pts);

    H = tildeH + HJ;

    quiver3wrapper(eval_pts,H,'red');
    out = [];
    
end