function [X, W] = quad1_cross(Xqud, Wqud)



        n1 = Xqud(:, 1);
        n2 = Xqud(:, 2);
        z1 = Xqud(:, 3);
        z2 = Xqud(:, 4);
        z3 = Xqud(:, 5);
        
        
        oneColumn = 0*z1+1;
        
        Jac1 = Wqud .* z1.^4 .* z2.^3 .* z3.^2 .* n1;
        
        W1 = Jac1;
        X1 = [(1-z1), z1.*(1-z2), (1-z1), z1.*(1-z2), 0*oneColumn] + ...
                   z1.*z2.*z3.* [n1.*n2,...
                    0*oneColumn,...
                    0*oneColumn,...
                    n1,...
                    (1-n1)];
        
        W2 = Jac1;
        X2 = [(1-z1), z1.*(1-z2), (1-z1), z1.*(1-z2), 0*oneColumn] + ...
                   z1.*z2.*z3.* [oneColumn,...
                    0*oneColumn,...
                    0*oneColumn,...
                    n1.*n2,...
                    n1.*(1-n2)];
                
        W3 = Jac1;
        X3 = [(1-z1), z1.*(1-z2), (1-z1), z1.*(1-z2), 0*oneColumn] + ...
                   z1.*z2.*z3.* [n1,...
                    0*oneColumn,...
                    0*oneColumn,...
                    n1.*n2,...
                    (1-n1.*n2)];
        W4 = Jac1;
        X4 = [(1-z1), z1.*(1-z2), (1-z1), z1.*(1-z2), 0*oneColumn] + ...
                   z1.*z2.*z3.* [n1.*n2,...
                    n1.*(1-n2),...
                    0*oneColumn,...
                    0*oneColumn,...
                    oneColumn];
                
        W5 = Jac1;
        X5 = [(1-z1), z1.*(1-z2), (1-z1), z1.*(1-z2), 0*oneColumn] + ...
                   z1.*z2.*z3.* [0*oneColumn,...
                    0*oneColumn,...
                    n1.*n2,...
                    n1.*(1-n2),...
                    (1-n1)];
        W6 = Jac1;
        X6 = [(1-z1), z1.*(1-z2), (1-z1), z1.*(1-z2), 0*oneColumn] + ...
                   z1.*z2.*z3.* [0*oneColumn,...
                    n1.*n2,...
                    n1,...
                    0*oneColumn,...
                    (1-n1)];
                
        W7 = Jac1;
        X7 = [(1-z1), z1.*(1-z2), (1-z1), z1.*(1-z2), 0*oneColumn] + ...
                   z1.*z2.*z3.* [0*oneColumn,...
                    oneColumn,...
                    n1.*n2,...
                    0*oneColumn,...
                    n1.*(1-n2)];
                
        W8 = Jac1;
        X8 = [(1-z1), z1.*(1-z2), (1-z1), z1.*(1-z2), 0*oneColumn] + ...
                   z1.*z2.*z3.* [0*oneColumn,...
                    n1,...
                    n1.*n2,...
                    0*oneColumn,...
                    (1-n1.*n2)];
            
        Jac2 = Wqud .* z1.^4 .* z2.^3 .* z3.^2; 
        
        W9 = Jac2;
        X9 =  [(1-z1), z1.*(1-z2), (1-z1), z1.*(1-z2), 0*oneColumn] + ...
                   z1.*z2.*z3.* [n1,...
                    (1-n1),...
                    0*oneColumn,...
                    0*oneColumn,...
                    n2];
                
                
                W = [W1;W2;W3;W4;W5;W6;W7;W8;W9];
                X = [X1;X2;X3;X4;X5;X6;X7;X8;X9];
                

end